mysql:
  image : mysql:5.7
  ports:
    - "3306:3306"
  volumes:
    - ~/db/mysql:/var/lib/mysql
    - ./config.cnf:/etc/mysql/conf.d/config.cnf
  environment:
    MYSQL_USER: admin
    MYSQL_PASSWORD: admin
    MYSQL_DATABASE: bills-db
    MYSQL_ROOT_PASSWORD: root
  container_name: mysql